# Generated by Django 3.2.25 on 2025-01-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitySalaryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата (в рублях)')),
                ('vacancy_count', models.IntegerField(verbose_name='Количество вакансий')),
            ],
            options={
                'verbose_name': 'Уровень зарплат по городам',
                'verbose_name_plural': 'Уровень зарплат по городам',
                'ordering': ['-average_salary'],
            },
        ),
        migrations.CreateModel(
            name='CityVacancyShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('vacancy_share', models.FloatField(verbose_name='Доля вакансий (%)')),
                ('vacancy_count', models.IntegerField(verbose_name='Количество вакансий')),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам',
                'verbose_name_plural': 'Доля вакансий по городам',
                'ordering': ['-vacancy_share'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10, verbose_name='Код валюты')),
                ('exchange_rate', models.FloatField(verbose_name='Курс к рублю')),
                ('date', models.DateField(verbose_name='Дата курса')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.CreateModel(
            name='YearlySalaryDynamics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата (в рублях)')),
            ],
            options={
                'verbose_name': 'Динамика зарплат по годам',
                'verbose_name_plural': 'Динамика зарплат по годам',
            },
        ),
        migrations.CreateModel(
            name='YearlyTopSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skill', models.CharField(max_length=100, verbose_name='Навык')),
                ('frequency', models.IntegerField(verbose_name='Частота упоминания')),
            ],
            options={
                'verbose_name': 'ТОП-20 навыков по годам',
                'verbose_name_plural': 'ТОП-20 навыков по годам',
                'ordering': ['-frequency'],
            },
        ),
        migrations.CreateModel(
            name='YearlyVacancyDynamics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('vacancy_count', models.IntegerField(verbose_name='Количество вакансий')),
            ],
            options={
                'verbose_name': 'Динамика количества вакансий по годам',
                'verbose_name_plural': 'Динамика количества вакансий по годам',
            },
        ),
    ]
