# Generated by Django 5.1.4 on 2025-01-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citysalarystatistics',
            name='salary_graph',
            field=models.ImageField(blank=True, null=True, upload_to='salary_graphs/', verbose_name='График зарплат'),
        ),
        migrations.AddField(
            model_name='cityvacancyshare',
            name='vacancy_share_graph',
            field=models.ImageField(blank=True, null=True, upload_to='vacancy_share_graphs/', verbose_name='График доли вакансий'),
        ),
        migrations.AddField(
            model_name='yearlysalarydynamics',
            name='html_data',
            field=models.TextField(blank=True, null=True, verbose_name='HTML данные для таблицы'),
        ),
        migrations.AddField(
            model_name='yearlyvacancydynamics',
            name='html_data',
            field=models.TextField(blank=True, null=True, verbose_name='HTML данные для таблицы'),
        ),
    ]
