# Generated by Django 5.1.4 on 2025-01-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_citysalarystatistics_salary_graph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('html_table', models.TextField(verbose_name='HTML таблица')),
                ('graph_image', models.ImageField(blank=True, null=True, upload_to='graphs/', verbose_name='График (PNG)')),
            ],
            options={
                'verbose_name': 'Раздел статистики',
                'verbose_name_plural': 'Разделы статистики',
            },
        ),
        migrations.DeleteModel(
            name='CitySalaryStatistics',
        ),
        migrations.DeleteModel(
            name='CityVacancyShare',
        ),
        migrations.DeleteModel(
            name='CurrencyExchangeRate',
        ),
        migrations.DeleteModel(
            name='YearlySalaryDynamics',
        ),
        migrations.DeleteModel(
            name='YearlyTopSkills',
        ),
        migrations.DeleteModel(
            name='YearlyVacancyDynamics',
        ),
    ]
