# Generated by Django 5.1.4 on 2025-01-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_generalstatistics_delete_citysalarystatistics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('html_table', models.TextField(verbose_name='HTML таблица уровня зарплат по годам')),
                ('graph_image', models.ImageField(blank=True, null=True, upload_to='graphs/', verbose_name='График уровня зарплат (PNG)')),
                ('vacancy_html_table', models.TextField(verbose_name='HTML таблица количества вакансий по годам')),
                ('vacancy_graph_image', models.ImageField(blank=True, null=True, upload_to='graphs/', verbose_name='График количества вакансий (PNG)')),
            ],
            options={
                'verbose_name': 'Статистика востребованности',
                'verbose_name_plural': 'Статистика востребованности',
            },
        ),
    ]
