# Generated by Django 5.1.4 on 2025-01-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_demandstatistics_vacancy_graph_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('html_table', models.TextField(verbose_name='HTML таблица')),
                ('graph_image', models.ImageField(blank=True, null=True, upload_to='graphs/', verbose_name='График (PNG)')),
            ],
            options={
                'verbose_name': 'География',
                'verbose_name_plural': 'География',
            },
        ),
    ]
