# Generated by Django 5.1.4 on 2025-01-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание вакансии')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Навыки')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('salary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Оклад')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at'],
            },
        ),
    ]
